let callCount = 0

export default function (req, res) {
  callCount++
  console.log(`[cache] Server hit #${callCount}`)

  res.writeHead(200, { 'Content-Type': 'application/json' })
  res.end(
    JSON.stringify({
      code: 0,
      data: {
        serverHit: callCount,
        timestamp: Date.now(),
        message: 'This response was generated by the server',
      },
      message: 'ok',
    }),
  )
}
